#!/bin/bash
mkdir -p data
opencv_traincascade -data data -vec './positives_64_64_64x64.vec' \
	-bg './neg.bg' \
	-numPos 900 -numNeg 2000 -numStages 13 \
	-precalcValBufSize 1024 -precalcIdxBufSize 1024 \
	-featureType LBP \
	-minHitRate 0.995 -maxFalseAlarmRate 0.5 \
	-w 64 -h 64
