#!/bin/bash
mkdir -p data
opencv_traincascade -data data -vec './pos.vec' \
	-bg './neg.bg' \
	-numPos 600 -numNeg 1200 -numStages 20 \
	-precalcValBufSize 1024 -precalcIdxBufSize 1024 \
	-featureType LBP \
	-minHitRate 0.995 -maxFalseAlarmRate 0.5 \
	-w 32 -h 32
